apiVersion: networking.superorbital.io/v1beta1
kind: TestSuite
metadata:
  name: namespaces
spec:
  testCases:
    - description: Pod in namespace a **cannot** reach api.prod
      expect: Fail
      from:
        deployment:
          name: web
          namespace: a
      to:
        address: api.proxy:80
    - description: Pod in namespace b **can** reach api.prod
      expect: Pass
      from:
        deployment:
          name: web
          namespace: b
      to:
        address: api.prod:80
